# Generated by Django 2.2.1 on 2019-06-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190618_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dolist',
            old_name='_line',
            new_name='line',
        ),
    ]
